<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>zuijin.ExcelTemplate</AssemblyName>
    <RepositoryUrl Label="GitHub">https://github.com/zuijin/ExcelTemplate</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="C:\Data\Code\ExcelTemplate\src\README.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CompareNETObjects" Version="4.84.0" />
    <PackageReference Include="NPOI" Version="2.8.0" />
  </ItemGroup>

</Project>
